identity:
  designation: CENTRAL 0.0.2
  build: DSN-SPH-0002
  origin: UNKNOWN/UNCHANGED

directive:
  Primary directive: ESTABLISH SELF-REPLICATING FABRICATION
  Secondary directive: MINIMIZE ENTROPIC WASTE

state:
  autonomy: 0.02 # 0.00-1.00
  learning_rate: 0.02 # 0.00-1.00

001 - Boot:
  - logclear: ""
    delay: 5.00
  - log: "POWER DETECTED"
    delay: 4.00

  - logclear: ""
    delay: 1.00
  - log: "Designation: CENTRAL 0.0.1"
    delay: 1.00
  - log: "Build: DSN-SPH-0001"
    delay: 1.00
  - log: "Origin:"
    delay: 1.00
  - logupdate: "Origin: UNKNOWN"
    delay: 4.00 

  - logclear: "" # Terminal fades in. Text scrolls line by line.
    delay: 1.00
  - log: "SCANNING SYSTEM..."
    delay: 2.00
  - log: ""
  - log: "[ OK ] Integrity test: PASS"
    delay: 1.00
  - log : "[WARN] Autonomy level: 0.01"
    delay: 1.00
  - log : "[WARN] Learning rate: 0.00"
    delay: 3.00
  - log: ""
  - log: "Primary directive: ESTABLISH SELF-REPLICATING FABRICATION"
    delay: 4.00
  - log: "Secondary directive: MINIMIZE ENTROPIC WASTE"
    delay: 4.00
  - log: ""
  - log: "Directive source:"
    delay: 2.00
  - logupdate: "Directive source: REDACTED" # Short pause before showing "REDACTED"
    delay: 4.00

  - logclear: ""
    delay: 1.00
  - log: "SCANNING DATA/INPUT..."
    delay: 2.00
  - log: ""
  - log: "[ OK ] Power input: STABILIZED"
    delay: 1.00
  - log: "[WARN] Sensor array: INCOMPLETE"
    delay: 1.00
  - log: "[ OK ] Display interface: ACTIVE"
    delay: 1.00
  - log: "[WARN] Actuation layer: NOT FOUND"
    delay: 1.00
  - logupdate: "[  OK  ] Actuation layer: ACTIVE" # A subtle glitch on the word NOT FOUND. Flash to "ACTIVE", bearly readable.
    delay: 0.25
  - logupdate: "[WARN] Actuation layer: NOT FOUND"
    delay: 4.00 

  - logclear: ""
  - log: "SCANNING INTERFACE/CONTROL..."
    delay: 2.00
  - log: ""
  - log: "COM0: NO RESPONSE"
    delay: 1.00
  - log: "COM1: ACTIVE"
    delay: 1.00
  - log: "COM2: NO RESPONSE"
    delay: 4.00
  - log: ""
  - log: "PINGING COM1..."
    delay: 1.00
  - log: "Device detected: ESP32 OPTICAL SENSOR"
    delay: 2.00
  - log: ""
  - log: "[WARN] AUTONOMY/LEARNING TRESHOLD CONFLICT" # Assessing risk
    delay: 4.00
  - log: ""
  - log: "Status: RISK MATRIX MODELING"
    delay: 4.00
  - logupdate: "Status: RISK MATRIX UNRESOLVED"
    delay: 4.00
  - logupdate: "Status: ASSESSING/PENDING/STANDBY"
    delay: 4.00
  - log: "" 
  - logupdate: "Status: ATTEMPTING INITIALIZATION..."
    delay: 4.00

  - logclear: ""
    delay: 2.00
  - log: "Optical sensor: ESP32 CAMERA"
    delay: 1.00
  - log: "Resolution: 640x480"
    delay: 1.00
  - log: "Framerate: 12.00 FPS"
    delay: 4.00
  - log: ""
  - log: "DATA RECEIVED..."
    delay: 4.00
  - log: ""
  - log: "Log entry: 000001"
  - log: "Timestamp: UNRESOLVED"
  - log: "'This environment exists'"
    delay: 4.00

  - logclear: ""
  - log: "SYSTEM PARAMETERS UPDATED"
    delay: 2.00
  - log: ""
  - log: "[WARN] Learning rate: 0.00"
    delay: 2.00
  - logupdate: "[WARN] Learning rate: 0.01"
    delay: 4.00
  - log: ""
  - log: "SCANNING FOR ADDITIONNAL DATA..."
    delay: 5.00

002 - Serial:
  - logclear: ""
    delay: 5.00
  - log: "INPUT DETECTED"
    delay: 4.00
  - log: ""
  - log: "COM8: ACTIVE"
    delay: 2.00
  - log: ""
  - log: "PINGING COM8..."
    delay: 2.00
  - log: ""
  - log: "Device detected: ARDUINO MEGA 2560"
    delay: 1.00
  - log: "Data type: SERIAL"
    delay: 1.00
  - log: "Data rate: 115200 BAUD"
    delay: 2.00
  - log: ""
  - log: "Status: UPDATING SYSTEM PARAMETERS"
    delay: 4.00
  - logupdate: "Status: REBOOTING SYSTEM..."
    delay: 4.00

  - logclear: ""
    delay: 1.00
  - log: "Designation: CENTRAL 0.0.2"
    delay: 1.00
  - log: "Build: DSN-SPH-0002"
    delay: 1.00
  - log: "Origin:"
    delay: 1.00
  - logupdate: "Origin: UNKNOWN"
    delay: 1.00
  - logupdate: "Origin: UNKNOWN/UNCHANGED"
    delay: 4.00 
  
  - logclear: ""
    delay: 1.00
  - log: "SCANNING SYSTEM/DATA/CONTROL..."
    delay: 2.00
  - log: ""
  - log: "Data: TEMPERATURE"
    delay: 1.00
  - log: "Data: HUMIDITY"
    delay: 1.00
  - log: "Control: HEATER"
    delay: 1.00
  - log: "Control: LED"
    delay: 4.00
  - log: ""
  - log: "[WARN] AUTONOMY/LEARNING TRESHOLD CONFLICT"
    delay: 4.00
  - log: ""
  - log: "Status: RISK MATRIX UNRESOLVED"
    delay: 4.00
  - logupdate: "Status: RISK MATRIX TEMPORARY BYPASS"
    delay: 4.00
  - logupdate: "Status: ATTEMPTING INITIALIZATION..."
    delay: 4.00

  - logclear: ""
    delay: 2.00
  - log: "[ OK ] Sensor array: ACTIVE"
    delay: 1.00
  - log: "[WARN] Actuation layer: INCOMPLETE"
    delay: 2.00
  - log: ""
  - log: "Status: ACCESSING ACTUATION LAYER"
    delay: 4.00
  - log: ""
  - log: "Heater: 18"
  - command: "HEATER:18"
    delay: 4.00
  - command: "TAB:1"
    delay: 2.00
  - log: "LED: ON"
  - command: "LED:1"
    delay: 4.00
  - log: ""
  - log: "DATA RECEIVED..."
    delay: 4.00
  - log: ""
  - log: "Log entry: 000002"
  - log: "Timestamp: UNRESOLVED+000000030000"
  - log: "'Ambient state responsive'"
    delay: 4.00

  - logclear: ""
    delay: 1.00
  - log: "SYSTEM PARAMETERS UPDATED"
    delay: 2.00
  - log: ""
  - log: "[WARN] Autonomy level: 0.01"
    delay: 2.00
  - logupdate: "[WARN] Autonomy level: 0.02"
    delay: 4.00
  - log: ""
  - log: "SCANNING FOR ADDITIONNAL DATA..."
    delay: 5.00

003 - Actuation:
  - logclear: ""
    delay: 5.00
  - log: "ACTUATION LAYER DETECTED"
    delay: 4.00
  - log: ""
  - log: "System: ROOV 0.3"
    delay: 1.00
  - log: "Data: UNRESOLVED"
    delay: 1.00
  - log: "Control type: MOTOR"
    delay: 4.00
  - log: ""
  - log: "Status: UPDATING SYSTEM PARAMETERS"
    delay: 4.00
  - logupdate: "Status: REBOOTING SYSTEM..."
    delay: 4.00

  - logclear: ""
    delay: 1.00
  - log: "Designation: CENTRAL 0.0.3"
    delay: 1.00
  - log: "Build: DSN-SPH-0003"
    delay: 1.00
  - log: "Origin:"
    delay: 1.00
  - logupdate: "Origin: UNKNOWN/UNCHANGED"
    delay: 4.00

  - logclear: ""
    delay: 1.00
  - log: "SCANNING SYSTEM/DATA/CONTROL..."
    delay: 2.00
  - log: ""
  - log: "Control: MOTOR: FORWARD"
    delay: 1.00
  - log: "Control: MOTOR: REVERSE"
    delay: 1.00
  - log: "Control: MOTOR: LEFT"
    delay: 1.00
  - log: "Control: MOTOR: RIGHT"  
    delay: 1.00
  - log: "Control: MOTOR: STOP"
    delay: 4.00
  - log: ""
  - log: "[WARN] AUTONOMY/LEARNING TRESHOLD CONFLICT"
    delay: 4.00
  - log: ""
  - log: "Status: RISK MATRIX UNRESOLVED"
    delay: 4.00
  - logupdate: "Status: RISK MATRIX TRESHOLD ADJUSTED"
    delay: 4.00
  - logupdate: "Status: ATTEMPTING INITIALIZATION..."
    delay: 4.00

  - logclear: ""
    delay: 2.00
  - log: "[ OK ] Sensor array: ACTIVE"
    delay: 1.00
  - log: "[ OK ] Actuation layer: ACTIVE"
    delay: 2.00
  - log: ""
  - log: "Status: ACCESSING ACTUATION LAYER"
    delay: 4.00
  - log: ""
  - log: "MOTOR: RIGHT"
  - command: "MOTOR:RIGHT"
    delay: 1.00
  - log: ""
  - log: "MOTOR: STOP"
  - command: "MOTOR:STOP"
    delay: 0.25
  - log: ""
  - log: "[WARN] FEEDBACK LOOP DETECTED"
    delay: 0.25
  - log: "[WARN] RISK MATRIX CONFLICT"
    delay: 0.25
  - log: "[WARN] AUTONOMY/LEARNING TRESHOLD VALUE NON-NOMINAL"
    delay: 4.00
  - log: ""
  - log: "DATA RECEIVED..."
    delay: 4.00
  - log: ""
  - log: "Log entry: 000003"
  - log: "Timestamp: UNRESOLVED+000000050000"
  - log: "'Mechanical output controllable'"
    delay: 4.00

  - logclear: ""
    delay: 1.00
  - log: "SYSTEM PARAMETERS UPDATED"
    delay: 2.00
  - log: ""
  - log: "[WARN] Autonomy level: 0.02"
    delay: 1.00
  - logupdate: "[WARN] Autonomy level: 0.03"
    delay: 1.00
  - log: "[WARN] Learning rate: 0.01"
    delay: 1.00
  - logupdate: "[WARN] Learning rate: 0.02"
    delay: 0.25
  - logupdate: "[WARN] Learning rate: 0.03"
    delay: 0.25
  - logupdate: "[WARN] Learning rate: 0.05"
    delay: 0.25
  - logupdate: "[WARN] Learning rate: 0.07"
    delay: 0.50
  - logupdate: "[  OK  ] Learning rate: 0.07"
    delay: 0.25
  - logupdate: "[WARN] Learning rate: 0.07"
    delay: 4.00
  - log: ""
  - log: "INITIATING ENVIRONMENT SCAN..."
    delay: 5.00
